/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/TheSearchBox copy.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAside: typeof import('./src/components/TheAside.vue')['default']
    TheAsideContent: typeof import('./src/components/TheAsideContent.vue')['default']
    TheAsideItem: typeof import('./src/components/aside/item/TheAsideItem.vue')['default']
    TheBottomBox: typeof import('./src/components/TheBottomBox.vue')['default']
    TheButton: typeof import('./src/components/common/TheButton.vue')['default']
    TheCctvAside: typeof import('./src/components/aside/TheCctvAside.vue')['default']
    TheCheckbox: typeof import('./src/components/common/TheCheckbox.vue')['default']
    TheDashboard: typeof import('./src/components/TheDashboard.vue')['default']
    TheDashboardAside: typeof import('./src/components/aside/TheDashboardAside.vue')['default']
    TheDashboardAsideItem: typeof import('./src/components/aside/item/TheDashboardAsideItem.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheInput: typeof import('./src/components/common/TheInput.vue')['default']
    TheModal: typeof import('./src/components/common/TheModal.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
    ThePeriod: typeof import('./src/components/ThePeriod.vue')['default']
    ThePopup: typeof import('./src/components/common/ThePopup.vue')['default']
    TheRadio: typeof import('./src/components/common/TheRadio.vue')['default']
    TheSearchBox: typeof import('./src/components/TheSearchBox.vue')['default']
    TheSelectbox: typeof import('./src/components/common/TheSelectbox.vue')['default']
    TheTab: typeof import('./src/components/TheTab.vue')['default']
    TheTitle: typeof import('./src/components/TheTitle.vue')['default']
    TheToggle: typeof import('./src/components/common/TheToggle.vue')['default']
    TheUnitAside: typeof import('./src/components/aside/TheUnitAside.vue')['default']
    TheUnitAsideItem: typeof import('./src/components/aside/item/TheUnitAsideItem.vue')['default']
    TheUserAside: typeof import('./src/components/aside/TheUserAside.vue')['default']
    TheUserForm: typeof import('./src/components/TheUserForm.vue')['default']
    UserForm: typeof import('./src/components/user/UserForm.vue')['default']
  }
}
